/*CREATE DATABASE BDTEST

USE master
*/

USE BDTEST;

SELECT * FROM TM_CATEGORIA

INSERT INTO TM_CATEGORIA
(CAT_NOM,FECH_CREA,EST)
VALUES
('LAPTOPS', GETDATE(),1)


SELECT * FROM TM_PRODUCTO

INSERT INTO TM_PRODUCTO
(CAT_ID,PROD_NOM,FECH_CREA,EST)
VALUES
(3,'ASUS',GETDATE(),1)

INSERT INTO TM_PRODUCTO
(CAT_ID,PROD_NOM,FECH_CREA,EST)
VALUES
(3,'MSI',GETDATE(),1)

UPDATE TM_PRODUCTO
SET
	FECH_CREA = GETDATE()
WHERE
	FECH_CREA IS NULL

SELECT * FROM TM_PRODUCTO WHERE PROD_ID = 3

UPDATE TM_PRODUCTO
SET
	EST = 0
WHERE
	PROD_ID = 6

SELECT * FROM TM_PRODUCTO
WHERE
CAT_ID = 3

SELECT * FROM TM_PRODUCTO
WHERE
CAT_ID IN (1,3)

SELECT * FROM TM_PRODUCTO
WHERE
PROD_NOM LIKE '%MABE%'

SELECT * FROM TM_PRODUCTO
WHERE
PROD_NOM LIKE '%A%'

--Parte 2

--Creacion del procedure
CREATE PROCEDURE SP_L_PRODUCTO_02
@PROD_ID INT
AS
BEGIN
SELECT        
	TM_PRODUCTO.PROD_ID, 
	TM_PRODUCTO.CAT_ID, 
	TM_PRODUCTO.PROD_NOM, 
	TM_CATEGORIA.CAT_NOM
FROM            
	TM_CATEGORIA INNER JOIN
    TM_PRODUCTO ON TM_CATEGORIA.CAT_ID = TM_PRODUCTO.CAT_ID
WHERE
	TM_PRODUCTO.PROD_ID = @PROD_ID
END

--Ejecucion del procedure
EXEC SP_L_PRODUCTO_01

--Para ver el codigo del procedure
SP_HELPTEXT SP_L_PRODUCTO_01

--Ejecucion del procedure
EXEC SP_L_PRODUCTO_02 1

--Para ver el codigo del procedure
SP_HELPTEXT SP_L_PRODUCTO_02

ALTER PROCEDURE SP_L_PRODUCTO_02  
@PROD_ID INT  
AS  
BEGIN  
SELECT          
 TM_PRODUCTO.PROD_ID,   
 TM_PRODUCTO.CAT_ID,   
 TM_PRODUCTO.PROD_NOM,   
 TM_CATEGORIA.CAT_NOM,
 TM_PRODUCTO.EST
FROM              
 TM_CATEGORIA INNER JOIN  
    TM_PRODUCTO ON TM_CATEGORIA.CAT_ID = TM_PRODUCTO.CAT_ID  
WHERE  
 TM_PRODUCTO.PROD_ID = @PROD_ID  
END

SP_L_PRODUCTO_02 1

--PARTE 3 

CREATE PROCEDURE SP_L_CATEGORIA_01
AS
BEGIN
	SELECT * FROM TM_CATEGORIA
END

DROP PROCEDURE SP_L_CATEGORIA_01

